version: '3'
services:
  db:
    image: postgres:9.6.16
    container_name: database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: mobile